# (C) Copyright 2016 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#
# Warning:
# 	mx6ullevk_siklu_pcb19x_linux.c file used also for EVK
#


obj-y  := mx6ullevk.o \
	 mx6ullevk_siklu_pcb19x.o mx6ullevk_siklu_api.o \
	 mx6ullevk_siklu_mutual_env.o \
	 mx6ullevk_siklu_pcb19x_linux.o

obj-$(CONFIG_SIKLU_BOARD) += mx6ullevk_siklu_pcb19x_spi.o	\
	mx6ullevk_siklu_hw.o  mx6ullevk_siklu_pcb19x_i2c.o \
	mx6ullevk_siklu_soho.o mx6ullevk_siklu_eth.o \
	mx6ullevk_siklu_clause45.o mx6ullevk_siklu_mdio.o \
	mx6ullevk_siklu_pcb19x_syseeprom.o mx6ullevk_siklu_pcb19x_sf.o \
	mx6ullevk_siklu_pcb19x_se_environment.o \
	mx6ullevk_siklu_mem_test.o mx6ullevk_siklu_pcb19x_led.o \
	mx6ullevk_siklu_bubt.o mx6ullevk_siklu_si5344d_pll.o \
	mx6ullevk_siklu_ethernity.o

